export const BenefitstoPages: Record<string, number[]> = {
  personaEquipmentExpenses: [8],
  other: [1, 2, 17],
  sixRoad: [22],
  vacationCancelation: [23, 24],
  vacationVouchers: [28, 29],
  bonusesExplanations: [30, 31, 32, 33, 34],
  emotionalSupport: [18, 19, 20],
  professionalDevelopment: [6],
  privateLessons: [4],
  tuitionRefund: [5],
  reCourse: [4],
  unemployedDamages: [13],
  selfEmployed: [16],
  unemployedPartner: [11],
  exDamages: [3, 12],
  parentalLeave: [14],
  babysitter: [7],
  summerCamp: [27],
  household: [9],
  dogPension: [10],
  livingAbroad: [15],
  additionalEmotionalSupport: [21],
  movingRefund: [25],
  damagedWhileAmKelavi: [26],
};
